//****************************************************************************
//  NARS2000 -- Common Prototypes
//****************************************************************************

#ifndef COMPRO_INCLUDED
#define COMPRO_INCLUDED

#include "assign.pro"
#include "bjhash.pro"
#include "common.pro"
#include "convert.pro"
#include "debug.pro"
#include "dfnhdr.pro"
#include "display.pro"
#include "dtoa.pro"
////lude "editctrl.pro"
#include "editfcn.pro"
#include "editmat.pro"
#include "editvec.pro"
#include "exec.pro"
#include "fastbool.pro"
#include "free.pro"
#include "g_fmt.pro"
#include "main.pro"
#include "parse.pro"
#include "pf_bar.pro"
#include "pf_circle.pro"
#include "pf_colonbar.pro"
#include "pf_comma.pro"
#include "pf_cslope.pro"
#include "pf_cstar.pro"
#include "pf_cstile.pro"
#include "pf_dcaret.pro"
#include "pf_domino.pro"
#include "pf_dstile.pro"
#include "pf_dtackjot.pro"
#include "pf_epsilon.pro"
#include "pf_equal.pro"
#include "pf_equalund.pro"
#include "pf_iota.pro"
#include "pf_lcaret.pro"
#include "pf_lcaretund.pro"
#include "pf_lshoe.pro"
#include "pf_ltack.pro"
#include "pf_ndcaret.pro"
#include "pf_nequal.pro"
#include "pf_nucaret.pro"
#include "pf_plus.pro"
#include "pf_qdot.pro"
#include "pf_query.pro"
#include "pf_rcaret.pro"
#include "pf_rcaretund.pro"
#include "pf_rho.pro"
#include "pf_rtack.pro"
#include "pf_slash.pro"
#include "pf_slope.pro"
#include "pf_squad.pro"
#include "pf_star.pro"
#include "pf_stile.pro"
#include "pf_tilde.pro"
#include "pf_times.pro"
#include "pf_uarrow.pro"
#include "pf_ucaret.pro"
#include "pf_ustile.pro"
#include "po_dieresis.pro"
#include "po_ditilde.pro"
#include "po_dot.pro"
#include "po_jot.pro"
#include "po_jotdot.pro"
#include "po_slash.pro"
#include "po_slope.pro"
#include "primfns.pro"
#include "primspec.pro"
#include "refcnt.pro"
#include "reg.pro"
//nclude "resdebug.pro"
#include "savews.pro"
#include "sessman.pro"
#include "strand.pro"
#include "symtab.pro"
#include "symtrans.pro"
#include "syscmds.pro"
#include "sysfns.pro"
#include "sysvars.pro"
#include "tabctrl.pro"
#include "translate.pro"
#include "ver.pro"
#if RESDEBUG
#include "resdebug.pro"
#endif
#include <QDebug.pro>

#endif

//***************************************************************************
//  End of File: compro.h
//***************************************************************************
