# Microsoft Visual C++ generated build script

.SUFFIXES: .DEP .DEV .PRO .Y

NAME = NARS2000                 # Directory name
ZIPNAME = NARS-SRC              # Zip file name
ENAME = NARS2000                # Executable name
PROJPATH = $(SRCROOT)$(NAME)\trunk\  # Project path
BIN = $(PROJPATH)binaries\      # Binaries directory
DEBUG=0
A=$(PROJPATH)Images\            # Images & artwork
BC=$(BIN)COM\                   # Directory for common binaries
WS=WineHQ\                      # Wine source
OLDPATH = $(PATH)               # Save the current path
CYGWIN=C:\cygwin\               # Dir for cygwin
GSLINC=$(CYGWIN)usr\include\    # Directory of GSL includes
##GSLINC=$(CYGWIN)usr\src\gsl-1.9-1\src\gsl-1.9\ # Directory of GSL includes
##GSLLIB=$(CYGWIN)usr\src\gsl-1.9-1\src\gsl-1.9\ # Directory of GSL libs
GSLLIB=gsl\                     # Directory of GSL libs

MV=makever

WIN=32
WDEF=_WIN$(WIN)

!if "$(DEBUG)" == "1"
RESDEBUG=1
CFLAGS_DEBUG=/Zd /D "DEBUG" /D "RESDEBUG=$(RESDEBUG)"
!else
RESDEBUG=0
CFLAGS_DEBUG=/D "RESDEBUG=$(RESDEBUG)" /Ox
!endif

CFLAGS_WEXE = /nologo /Gs /GA /W3 /WX /Zp1 $(CFLAGS_DEBUG) /D $(WDEF)
LFLAGS_WEXE = /NOLOGO /MAP
LIBS_WEXE = GDI32.LIB           \
            USER32.LIB          \
            VERSION.LIB         \
            COMDLG32.LIB        \
            SHELL32.LIB         \
            ADVAPI32.LIB        \
            COMCTL32.LIB        \
            libc.lib            \
            libgsl-double.a     \
            libgslcblas-double.a

RCFLAGS =
RESFLAGS =
ASMOPTS=/coff

RUNFLAGS =
DEFFILE = main.DEF
OBJS_EXT =
MAPFILE = main.MAP
!if "$(DEBUG)" == "1"
RCDEFINES = /D $(WDEF) /D BUILD_BETA
!else
RCDEFINES = /D $(WDEF)
!endif

ASM=masm
AFLAGS=/Mu /DDEBUG=$(DEBUG)
!if "$(VS)" == "1"
O=DEBUG\                        # define output directory for intermediate files
B=$(BIN)D\                      # ...                         binaries
!else
!if "$(DEBUG)" == "1"
O=RET\D\                        # define output directory for intermediate files
B=$(BIN)D\                      # ...                         binaries
!else
O=RET\ND\                       # define output directory for intermediate files
B=$(BIN)ND\                     # ...                         binaries
!endif
!endif
HLP=$(HCDIR)HCRTF.EXE           # Path to HCRTF
P=R:\$(NAME)\                   # Full path to . dir for HCRTF
I=$(SRCROOT)INC\                # .INC directory
H=$(SRCROOT)INCLUDE\            # .INCLUDE directory
L=$(SRCROOT)LIB\                # .LIB directory

M98=N:\                         # Win98 build
###M98=L:\VC98\                    # Win98 build
I98=$(PROJPATH);$(M98)INCLUDE;$(MSVC)INCLUDE;$(GSLINC)
L98=$(M98)LIB;$(MSVC)LIB;$(CYGWIN)lib;$(GSLLIB).libs\;$(GSLLIB)cblas\.libs\

LD=$(M98)BIN\link
CC=$(M98)BIN\cl
RC=$(M98)BIN\rc


ALL:    DIR                 \
        PRO                 \
        DEP                 \
        $(O)$(ENAME).EXE    \
        $(L)$(ENAME).EXE    \
        $(BC)$(ENAME).HLP   \
        $(L)$(ENAME).HLP    \
        $(O)$(MV).exe       \
        $(L)$(MV).exe       \
        $(ENAME).ver

CLEAN:
        @del /Q $(O)*.*

DEL:
        @del /Q $(O)*.*

DIR:
        @Set PATH=$(BC)
        @vdir -q -c $(O) $(B) $(BC) >NUL
        @Set PATH=$(OLDPATH)

{}.rc{$(O)}.res:
        @Set INCLUDE=$(I98);$(H);$(O)
        @if exist $@ del $@
        @$(RC) $(RCFLAGS) $(RCDEFINES) -r -fo$@ %s

{}.y{$(O)}.c:
        @Set INCLUDE=$(I98);$(H);$(O)
        bison -o$(O)$(@B).c -v -r all -l %s
########bison -o$(O)$(@B).c           -l %s

{}.c{$(O)}.obj:
        @Set INCLUDE=$(I98);$(H);$(O)
        @if exist $@ del $@
        @$(CC) $(CFLAGS_WEXE) /Fo$@ /c %s

{$(O)}.c{$(O)}.obj:
        @Set INCLUDE=$(I98);$(H);$(O)
        @if exist $@ del $@
        @$(CC) $(CFLAGS_WEXE) /Fo$@ /c %s

{$(WS)}.c{$(O)}.obj:
        @Set INCLUDE=$(WS).;$(WS)Include;$(WS)Include\Wine;$(WS)Include\msvcrt;.;$(O)
        @if exist $@ del $@
        @$(CC) $(CFLAGS_WEXE) /Fo$@ /c /D "UNICODE" %s

####################### DEPENDENCY GENERATION #################

DEP:                    \
$(O)assign.DEP          \
$(O)bjhash.DEP          \
$(O)common.DEP          \
$(O)convert.DEP         \
$(O)debug.DEP           \
$(O)dfnhdr.DEP          \
$(O)dispdbg.DEP         \
$(O)display.DEP         \
$(O)dtoa.DEP            \
$(O)editctrl.DEP        \
$(O)editfcn.DEP         \
$(O)editmat.DEP         \
$(O)editvec.DEP         \
$(O)errmsg.DEP          \
$(O)except.DEP          \
$(O)execdfn.DEP         \
$(O)fastbool.DEP        \
$(O)free.DEP            \
$(O)g_fmt.DEP           \
$(O)goto.DEP            \
$(O)immexec.DEP         \
$(O)main.DEP            \
$(O)parse.DEP           \
$(O)pf_bar.DEP          \
$(O)pf_circle.DEP       \
$(O)pf_colonbar.DEP     \
$(O)pf_comma.DEP        \
$(O)pf_cslope.DEP       \
$(O)pf_cstile.DEP       \
$(O)pf_cstar.DEP        \
$(O)pf_darrow.DEP       \
$(O)pf_dcaret.DEP       \
$(O)pf_deltastile.DEP   \
$(O)pf_domino.DEP       \
$(O)pf_dstile.DEP       \
$(O)pf_dtack.DEP        \
$(O)pf_dtackjot.DEP     \
$(O)pf_epsilon.DEP      \
$(O)pf_equal.DEP        \
$(O)pf_equalund.DEP     \
$(O)pf_index.DEP        \
$(O)pf_iota.DEP         \
$(O)pf_lcaret.DEP       \
$(O)pf_lcaretund.DEP    \
$(O)pf_lshoe.DEP        \
$(O)pf_ltack.DEP        \
$(O)pf_ndcaret.DEP      \
$(O)pf_nequal.DEP       \
$(O)pf_nucaret.DEP      \
$(O)pf_plus.DEP         \
$(O)pf_qdot.DEP         \
$(O)pf_query.DEP        \
$(O)pf_rcaret.DEP       \
$(O)pf_rcaretund.DEP    \
$(O)pf_rho.DEP          \
$(O)pf_rshoe.DEP        \
$(O)pf_rtack.DEP        \
$(O)pf_slash.DEP        \
$(O)pf_slope.DEP        \
$(O)pf_squad.DEP        \
$(O)pf_star.DEP         \
$(O)pf_stile.DEP        \
$(O)pf_tilde.DEP        \
$(O)pf_times.DEP        \
$(O)pf_uarrow.DEP       \
$(O)pf_ucaret.DEP       \
$(O)pf_ustile.DEP       \
$(O)pf_utack.DEP        \
$(O)pf_utackjot.DEP     \
$(O)po_dieresis.DEP     \
$(O)po_ditilde.DEP      \
$(O)po_dot.DEP          \
$(O)po_jot.DEP          \
$(O)po_jotdot.DEP       \
$(O)po_slash.DEP        \
$(O)po_slope.DEP        \
$(O)primfns.DEP         \
$(O)primspec.DEP        \
$(O)qdwa.DEP            \
$(O)qf_av.DEP           \
$(O)qf_cr.DEP           \
$(O)qf_dl.DEP           \
$(O)qf_dm.DEP           \
$(O)qf_dr.DEP           \
$(O)qf_error.DEP        \
$(O)qf_lc.DEP           \
$(O)qf_nc.DEP           \
$(O)qf_nl.DEP           \
$(O)qf_size.DEP         \
$(O)qf_sysid.DEP        \
$(O)qf_sysver.DEP       \
$(O)qf_tc.DEP           \
$(O)qf_ts.DEP           \
$(O)qf_type.DEP         \
$(O)qf_ucs.DEP          \
$(O)refcnt.DEP          \
$(O)reg.DEP             \
$(O)resdebug.DEP        \
$(O)savews.DEP          \
$(O)sessman.DEP         \
$(O)sort.DEP            \
$(O)strand.DEP          \
$(O)symtab.DEP          \
$(O)symtrans.DEP        \
$(O)syscmds.DEP         \
$(O)sysvars.DEP         \
$(O)tabctrl.DEP         \
$(O)tokenize.DEP        \
$(O)translate.DEP       \
$(O)ver.DEP             \
$(O)main.DEV            \
$(O)ver.DEV             \
$(O)version.DEV         \
$(O)yyfns.DEP

{$(O)}.C{$(O)}.DEP:
    @Set INCLUDE=$(I98);$(H);$(O)
    @Set PATH=$(BC)
####@echo depscan -q -s$(PROJPATH)$(O)=$$(O) %s
    @     depscan -q -s$(PROJPATH)$(O)=$$(O) %s > $@
    @Set PATH=$(OLDPATH)

{$(WS)}.C{$(O)}.DEP:
    @Set INCLUDE=$(WS).;$(WS)Include;$(WS)Include\Wine;$(WS)Include\msvcrt;.
    @Set PATH=$(BC)
####@echo depscan -q -s$(PROJPATH)$(O)=$$(O),$(WS)=$$(WS) %s
    @     depscan -q -s$(PROJPATH)$(O)=$$(O),$(WS)=$$(WS) %s > $@
    @Set PATH=$(OLDPATH)

{}.C{$(O)}.DEP:
    @Set INCLUDE=$(I98);$(H);$(O)
    @Set PATH=$(BC)
####@echo depscan -q -s$(PROJPATH)$(O)=$$(O) %s
    @     depscan -q -s$(PROJPATH)$(O)=$$(O) %s > $@
    @Set PATH=$(OLDPATH)

{}.RC{$(O)}.DEV:
    @Set INCLUDE=$(I98);$(H);$(O)
    @Set PATH=$(BC)
####@echo depscan -q -s$(PROJPATH)$(O)=$$(O) %s
    @     depscan -q -s$(PROJPATH)$(O)=$$(O) %s > $@
    @Set PATH=$(OLDPATH)

!if exist ($(O)assign.DEP)
!       include $(O)assign.DEP
!endif
!if exist ($(O)bjhash.DEP)
!       include $(O)bjhash.DEP
!endif
!if exist ($(O)common.DEP)
!       include $(O)common.DEP
!endif
!if exist ($(O)convert.DEP)
!       include $(O)convert.DEP
!endif
!if exist ($(O)debug.DEP)
!       include $(O)debug.DEP
!endif
!if exist ($(O)dfnhdr.DEP)
!       include $(O)dfnhdr.DEP
!endif
!if exist ($(O)dispdbg.DEP)
!       include $(O)dispdbg.DEP
!endif
!if exist ($(O)display.DEP)
!       include $(O)display.DEP
!endif
!if exist ($(O)dtoa.DEP)
!       include $(O)dtoa.DEP
!endif
!if exist ($(O)editctrl.DEP)
!       include $(O)editctrl.DEP
!endif
!if exist ($(O)editfcn.DEP)
!       include $(O)editfcn.DEP
!endif
!if exist ($(O)editmat.DEP)
!       include $(O)editmat.DEP
!endif
!if exist ($(O)editvec.DEP)
!       include $(O)editvec.DEP
!endif
!if exist ($(O)errmsg.DEP)
!       include $(O)errmsg.DEP
!endif
!if exist ($(O)except.DEP)
!       include $(O)except.DEP
!endif
!if exist ($(O)execdfn.DEP)
!       include $(O)execdfn.DEP
!endif
!if exist ($(O)fastbool.DEP)
!       include $(O)fastbool.DEP
!endif
!if exist ($(O)free.DEP)
!       include $(O)free.DEP
!endif
!if exist ($(O)g_fmt.DEP)
!       include $(O)g_fmt.DEP
!endif
!if exist ($(O)goto.DEP)
!       include $(O)goto.DEP
!endif
!if exist ($(O)immexec.DEP)
!       include $(O)immexec.DEP
!endif
!if exist ($(O)main.DEP)
!       include $(O)main.DEP
!endif
!if exist ($(O)parse.DEP)
!       include $(O)parse.DEP
!endif
!if exist ($(O)pf_bar.DEP)
!       include $(O)pf_bar.DEP
!endif
!if exist ($(O)pf_colonbar.DEP)
!       include $(O)pf_colonbar.DEP
!endif
!if exist ($(O)pf_comma.DEP)
!       include $(O)pf_comma.DEP
!endif
!if exist ($(O)pf_cslope.DEP)
!       include $(O)pf_cslope.DEP
!endif
!if exist ($(O)pf_cstile.DEP)
!       include $(O)pf_cstile.DEP
!endif
!if exist ($(O)pf_cstar.DEP)
!       include $(O)pf_cstar.DEP
!endif
!if exist ($(O)pf_darrow.DEP)
!       include $(O)pf_darrow.DEP
!endif
!if exist ($(O)pf_dcaret.DEP)
!       include $(O)pf_dcaret.DEP
!endif
!if exist ($(O)pf_deltastile.DEP)
!       include $(O)pf_deltastile.DEP
!endif
!if exist ($(O)pf_domino.DEP)
!       include $(O)pf_domino.DEP
!endif
!if exist ($(O)pf_dstile.DEP)
!       include $(O)pf_dstile.DEP
!endif
!if exist ($(O)pf_dtack.DEP)
!       include $(O)pf_dtack.DEP
!endif
!if exist ($(O)pf_dtackjot.DEP)
!       include $(O)pf_dtackjot.DEP
!endif
!if exist ($(O)pf_epsilon.DEP)
!       include $(O)pf_epsilon.DEP
!endif
!if exist ($(O)pf_equal.DEP)
!       include $(O)pf_equal.DEP
!endif
!if exist ($(O)pf_equalund.DEP)
!       include $(O)pf_equalund.DEP
!endif
!if exist ($(O)pf_index.DEP)
!       include $(O)pf_index.DEP
!endif
!if exist ($(O)pf_iota.DEP)
!       include $(O)pf_iota.DEP
!endif
!if exist ($(O)pf_lcaret.DEP)
!       include $(O)pf_lcaret.DEP
!endif
!if exist ($(O)pf_lcaretund.DEP)
!       include $(O)pf_lcaretund.DEP
!endif
!if exist ($(O)pf_lshoe.DEP)
!       include $(O)pf_lshoe.DEP
!endif
!if exist ($(O)pf_ltack.DEP)
!       include $(O)pf_ltack.DEP
!endif
!if exist ($(O)pf_ndcaret.DEP)
!       include $(O)pf_ndcaret.DEP
!endif
!if exist ($(O)pf_nequal.DEP)
!       include $(O)pf_nequal.DEP
!endif
!if exist ($(O)pf_nucaret.DEP)
!       include $(O)pf_nucaret.DEP
!endif
!if exist ($(O)pf_plus.DEP)
!       include $(O)pf_plus.DEP
!endif
!if exist ($(O)pf_qdot.DEP)
!       include $(O)pf_qdot.DEP
!endif
!if exist ($(O)pf_query.DEP)
!       include $(O)pf_query.DEP
!endif
!if exist ($(O)pf_rcaret.DEP)
!       include $(O)pf_rcaret.DEP
!endif
!if exist ($(O)pf_rcaretund.DEP)
!       include $(O)pf_rcaretund.DEP
!endif
!if exist ($(O)pf_rho.DEP)
!       include $(O)pf_rho.DEP
!endif
!if exist ($(O)pf_rshoe.DEP)
!       include $(O)pf_rshoe.DEP
!endif
!if exist ($(O)pf_rtack.DEP)
!       include $(O)pf_rtack.DEP
!endif
!if exist ($(O)pf_slash.DEP)
!       include $(O)pf_slash.DEP
!endif
!if exist ($(O)pf_slope.DEP)
!       include $(O)pf_slope.DEP
!endif
!if exist ($(O)pf_squad.DEP)
!       include $(O)pf_squad.DEP
!endif
!if exist ($(O)pf_star.DEP)
!       include $(O)pf_star.DEP
!endif
!if exist ($(O)pf_stile.DEP)
!       include $(O)pf_stile.DEP
!endif
!if exist ($(O)pf_tilde.DEP)
!       include $(O)pf_tilde.DEP
!endif
!if exist ($(O)pf_times.DEP)
!       include $(O)pf_times.DEP
!endif
!if exist ($(O)pf_uarrow.DEP)
!       include $(O)pf_uarrow.DEP
!endif
!if exist ($(O)pf_ucaret.DEP)
!       include $(O)pf_ucaret.DEP
!endif
!if exist ($(O)pf_ustile.DEP)
!       include $(O)pf_ustile.DEP
!endif
!if exist ($(O)pf_utack.DEP)
!       include $(O)pf_utack.DEP
!endif
!if exist ($(O)pf_utackjot.DEP)
!       include $(O)pf_utackjot.DEP
!endif
!if exist ($(O)po_dieresis.DEP)
!       include $(O)po_dieresis.DEP
!endif
!if exist ($(O)po_ditilde.DEP)
!       include $(O)po_ditilde.DEP
!endif
!if exist ($(O)po_dot.DEP)
!       include $(O)po_dot.DEP
!endif
!if exist ($(O)po_jot.DEP)
!       include $(O)po_jot.DEP
!endif
!if exist ($(O)po_jotdot.DEP)
!       include $(O)po_jotdot.DEP
!endif
!if exist ($(O)po_slash.DEP)
!       include $(O)po_slash.DEP
!endif
!if exist ($(O)po_slope.DEP)
!       include $(O)po_slope.DEP
!endif
!if exist ($(O)primfns.DEP)
!       include $(O)primfns.DEP
!endif
!if exist ($(O)primspec.DEP)
!       include $(O)primspec.DEP
!endif
!if exist ($(O)qdwa.DEP)
!       include $(O)qdwa.DEP
!endif
!if exist ($(O)qf_av.DEP)
!       include $(O)qf_av.DEP
!endif
!if exist ($(O)qf_cr.DEP)
!       include $(O)qf_cr.DEP
!endif
!if exist ($(O)qf_dl.DEP)
!       include $(O)qf_dl.DEP
!endif
!if exist ($(O)qf_dm.DEP)
!       include $(O)qf_dm.DEP
!endif
!if exist ($(O)qf_dr.DEP)
!       include $(O)qf_dr.DEP
!endif
!if exist ($(O)qf_error.DEP)
!       include $(O)qf_error.DEP
!endif
!if exist ($(O)qf_lc.DEP)
!       include $(O)qf_lc.DEP
!endif
!if exist ($(O)qf_nc.DEP)
!       include $(O)qf_nc.DEP
!endif
!if exist ($(O)qf_nl.DEP)
!       include $(O)qf_nl.DEP
!endif
!if exist ($(O)qf_size.DEP)
!       include $(O)qf_size.DEP
!endif
!if exist ($(O)qf_sysid.DEP)
!       include $(O)qf_sysid.DEP
!endif
!if exist ($(O)qf_sysver.DEP)
!       include $(O)qf_sysver.DEP
!endif
!if exist ($(O)qf_tc.DEP)
!       include $(O)qf_tc.DEP
!endif
!if exist ($(O)qf_ts.DEP)
!       include $(O)qf_ts.DEP
!endif
!if exist ($(O)qf_type.DEP)
!       include $(O)qf_type.DEP
!endif
!if exist ($(O)qf_ucs.DEP)
!       include $(O)qf_ucs.DEP
!endif
!if exist ($(O)refcnt.DEP)
!       include $(O)refcnt.DEP
!endif
!if exist ($(O)reg.DEP)
!       include $(O)reg.DEP
!endif
!if exist ($(O)resdebug.DEP)
!       include $(O)resdebug.DEP
!endif
!if exist ($(O)savews.DEP)
!       include $(O)savews.DEP
!endif
!if exist ($(O)sessman.DEP)
!       include $(O)sessman.DEP
!endif
!if exist ($(O)sort.DEP)
!       include $(O)sort.DEP
!endif
!if exist ($(O)strand.DEP)
!       include $(O)strand.DEP
!endif
!if exist ($(O)symtab.DEP)
!       include $(O)symtab.DEP
!endif
!if exist ($(O)symtrans.DEP)
!       include $(O)symtrans.DEP
!endif
!if exist ($(O)syscmds.DEP)
!       include $(O)syscmds.DEP
!endif
!if exist ($(O)sysvars.DEP)
!       include $(O)sysvars.DEP
!endif
!if exist ($(O)tabctrl.DEP)
!       include $(O)tabctrl.DEP
!endif
!if exist ($(O)tokenize.DEP)
!       include $(O)tokenize.DEP
!endif
!if exist ($(O)translate.DEP)
!       include $(O)translate.DEP
!endif
!if exist ($(O)ver.DEP)
!       include $(O)ver.DEP
!endif
!if exist ($(O)main.DEV)
!       include $(O)main.DEV
!endif
!if exist ($(O)ver.DEV)
!       include $(O)ver.DEV
!endif
!if exist ($(O)version.DEV)
!       include $(O)version.DEV
!endif
!if exist ($(O)yyfns.DEP)
!       include $(O)yyfns.DEP
!endif


####################### PROTOTYPE GENERATION #################

PRO:                    \
$(O)assign.PRO          \
$(O)bjhash.PRO          \
$(O)common.PRO          \
$(O)convert.PRO         \
$(O)debug.PRO           \
$(O)dfnhdr.PRO          \
$(O)dispdbg.PRO         \
$(O)display.PRO         \
$(O)dtoa.PRO            \
$(O)editctrl.PRO        \
$(O)editfcn.PRO         \
$(O)editmat.PRO         \
$(O)editvec.PRO         \
$(O)errmsg.PRO          \
$(O)except.PRO          \
$(O)execdfn.PRO         \
$(O)fastbool.PRO        \
$(O)free.PRO            \
$(O)g_fmt.PRO           \
$(O)goto.PRO            \
$(O)immexec.PRO         \
$(O)main.PRO            \
$(O)parse.PRO           \
$(O)pf_bar.PRO          \
$(O)pf_circle.PRO       \
$(O)pf_colonbar.PRO     \
$(O)pf_comma.PRO        \
$(O)pf_cslope.PRO       \
$(O)pf_cstile.PRO       \
$(O)pf_cstar.PRO        \
$(O)pf_darrow.PRO       \
$(O)pf_dcaret.PRO       \
$(O)pf_deltastile.PRO   \
$(O)pf_domino.PRO       \
$(O)pf_dstile.PRO       \
$(O)pf_dtack.PRO        \
$(O)pf_dtackjot.PRO     \
$(O)pf_epsilon.PRO      \
$(O)pf_equal.PRO        \
$(O)pf_equalund.PRO     \
$(O)pf_index.PRO        \
$(O)pf_iota.PRO         \
$(O)pf_lcaret.PRO       \
$(O)pf_lcaretund.PRO    \
$(O)pf_lshoe.PRO        \
$(O)pf_ltack.PRO        \
$(O)pf_ndcaret.PRO      \
$(O)pf_nequal.PRO       \
$(O)pf_nucaret.PRO      \
$(O)pf_plus.PRO         \
$(O)pf_qdot.PRO         \
$(O)pf_query.PRO        \
$(O)pf_rcaret.PRO       \
$(O)pf_rcaretund.PRO    \
$(O)pf_rho.PRO          \
$(O)pf_rshoe.PRO        \
$(O)pf_rtack.PRO        \
$(O)pf_slash.PRO        \
$(O)pf_slope.PRO        \
$(O)pf_squad.PRO        \
$(O)pf_star.PRO         \
$(O)pf_stile.PRO        \
$(O)pf_tilde.PRO        \
$(O)pf_times.PRO        \
$(O)pf_uarrow.PRO       \
$(O)pf_ucaret.PRO       \
$(O)pf_ustile.PRO       \
$(O)pf_utack.PRO        \
$(O)pf_utackjot.PRO     \
$(O)po_dieresis.PRO     \
$(O)po_ditilde.PRO      \
$(O)po_dot.PRO          \
$(O)po_jot.PRO          \
$(O)po_jotdot.PRO       \
$(O)po_slash.PRO        \
$(O)po_slope.PRO        \
$(O)primfns.PRO         \
$(O)primspec.PRO        \
$(O)qdwa.PRO            \
$(O)qf_av.PRO           \
$(O)qf_cr.PRO           \
$(O)qf_dl.PRO           \
$(O)qf_dm.PRO           \
$(O)qf_dr.PRO           \
$(O)qf_error.PRO        \
$(O)qf_lc.PRO           \
$(O)qf_nc.PRO           \
$(O)qf_nl.PRO           \
$(O)qf_size.PRO         \
$(O)qf_sysid.PRO        \
$(O)qf_sysver.PRO       \
$(O)qf_tc.PRO           \
$(O)qf_ts.PRO           \
$(O)qf_type.PRO         \
$(O)qf_ucs.PRO          \
$(O)refcnt.PRO          \
$(O)reg.PRO             \
$(O)resdebug.PRO        \
$(O)savews.PRO          \
$(O)sessman.PRO         \
$(O)sort.PRO            \
$(O)strand.PRO          \
$(O)symtab.PRO          \
$(O)symtrans.PRO        \
$(O)syscmds.PRO         \
$(O)sysvars.PRO         \
$(O)tabctrl.PRO         \
$(O)tokenize.PRO        \
$(O)translate.PRO       \
$(O)ver.PRO             \
$(O)yyfns.PRO

{}.C{$(O)}.PRO:
        @Set INCLUDE=$(I98);$(H);$(O)
        @$(CC) $(CFLAGS_WEXE) /c /Zg /DPROTO %s > $@

{$(O)}.C{$(O)}.PRO:
        @Set INCLUDE=$(I98);$(H);$(O)
        @$(CC) $(CFLAGS_WEXE) /c /Zg /DPROTO %s > $@

{$(WS)}.C{$(O)}.PRO:
        @Set INCLUDE=$(WS).;$(WS)Include;$(WS)Include\Wine;$(WS)Include\msvcrt;.
        @$(CC) $(CFLAGS_WEXE) /c /Zg /DPROTO /D "UNICODE" %s > $@

########################## UTILITY ROUTINES ##########################

$(O)DBGBRK.OBJ:         DBGBRK.ASM
        @if exist $@ del $@
        ml /I$(I) /DIS_$(WIN) /c /W3 /nologo $(ASMOPTS) /Fo $@ %s


############################# MAIN APP ROUTINES ######################

ICONS=$(A)About.ico     \
      $(A)Close.ico     \
      $(A)MF.ico        \
      $(A)SM.ico        \
      $(A)DB.ico        \
      $(A)FE.ico        \
      $(A)ME.ico        \
      $(A)VE.ico        \
      $(A)LineCont.bmp

## Cygwin-specific files
$(O)getreent.OBJ:       $(@B).C

## FP-specific files
$(O)dtoa.OBJ:           $(@B).C         $(DTOA_DEP)
$(O)g_fmt.OBJ:          $(@B).C         $(G_FMT_DEP)

## Bison-generated files
$(O)dfnhdr.C:           $(@B).Y
$(O)dfnhdr.OBJ:         $(O)$(@B).C     $(DFNHDR_DEP)
$(O)parse.C:            $(@B).Y
$(O)parse.OBJ:          $(O)$(@B).C     $(PARSE_DEP)

## WineHQ-specific files
$(O)editctrl.OBJ:       $(WS)$(@B).C    $(EDITCTRL_DEP)

## NARS-specific files
$(O)assign.OBJ:         $(@B).C         $(ASSIGN_DEP)
$(O)bjhash.OBJ:         $(@B).C         $(BJHASH_DEP)
$(O)common.OBJ:         $(@B).C         $(COMMON_DEP)
$(O)convert.OBJ:        $(@B).C         $(CONVERT_DEP)
$(O)debug.OBJ:          $(@B).C         $(DEBUG_DEP)
$(O)dispdbg.OBJ:        $(@B).C         $(DISPDBG_DEP)
$(O)display.OBJ:        $(@B).C         $(DISPLAY_DEP)
$(O)editfcn.OBJ:        $(@B).C         $(EDITFCN_DEP)
$(O)editmat.OBJ:        $(@B).C         $(EDITMAT_DEP)
$(O)editvec.OBJ:        $(@B).C         $(EDITVEC_DEP)
$(O)errmsg.OBJ:         $(@B).C         $(ERRMSG_DEP)
$(O)except.OBJ:         $(@B).C         $(EXCEPT_DEP)
$(O)execdfn.OBJ:        $(@B).C         $(EXECDFN_DEP)
$(O)fastbool.OBJ:       $(@B).C         $(FASTBOOL_DEP)
$(O)free.OBJ:           $(@B).C         $(FREE_DEP)
$(O)goto.OBJ:           $(@B).C         $(GOTO_DEP)
$(O)immexec.OBJ:        $(@B).C         $(IMMEXEC_DEP)
$(O)main.OBJ:           $(@B).C         $(MAIN_DEP)
$(O)pf_bar.OBJ:         $(@B).C         $(PF_BAR_DEP)
$(O)pf_circle.OBJ:      $(@B).C         $(PF_CIRCLE_DEP)
$(O)pf_colonbar.OBJ:    $(@B).C         $(PF_COLONBAR_DEP)
$(O)pf_comma.OBJ:       $(@B).C         $(PF_COMMA_DEP)
$(O)pf_cslope.OBJ:      $(@B).C         $(PF_CSLOPE_DEP)
$(O)pf_cstile.OBJ:      $(@B).C         $(PF_CSTILE_DEP)
$(O)pf_cstar.OBJ:       $(@B).C         $(PF_CSTAR_DEP)
$(O)pf_darrow.OBJ:      $(@B).C         $(PF_DARROW_DEP)
$(O)pf_dcaret.OBJ:      $(@B).C         $(PF_DCARET_DEP)
$(O)pf_deltastile.OBJ:  $(@B).C         $(PF_DELTASTILE_DEP)
$(O)pf_domino.OBJ:      $(@B).C         $(PF_DOMINO_DEP)
$(O)pf_dstile.OBJ:      $(@B).C         $(PF_DSTILE_DEP)
$(O)pf_dtack.OBJ:       $(@B).C         $(PF_DTACK_DEP)
$(O)pf_dtackjot.OBJ:    $(@B).C         $(PF_DTACKJOT_DEP)
$(O)pf_epsilon.OBJ:     $(@B).C         $(PF_EPSILON_DEP)
$(O)pf_equal.OBJ:       $(@B).C         $(PF_EQUAL_DEP)
$(O)pf_equalund.OBJ:    $(@B).C         $(PF_EQUALUND_DEP)
$(O)pf_index.OBJ:       $(@B).C         $(PF_INDEX_DEP)
$(O)pf_iota.OBJ:        $(@B).C         $(PF_IOTA_DEP)
$(O)pf_lcaret.OBJ:      $(@B).C         $(PF_LCARET_DEP)
$(O)pf_lcaretund.OBJ:   $(@B).C         $(PF_LCARETUND_DEP)
$(O)pf_lshoe.OBJ:       $(@B).C         $(PF_LSHOE_DEP)
$(O)pf_ltack.OBJ:       $(@B).C         $(PF_LTACK_DEP)
$(O)pf_ndcaret.OBJ:     $(@B).C         $(PF_NDCARET_DEP)
$(O)pf_nequal.OBJ:      $(@B).C         $(PF_NEQUAL_DEP)
$(O)pf_nucaret.OBJ:     $(@B).C         $(PF_NUCARET_DEP)
$(O)pf_plus.OBJ:        $(@B).C         $(PF_PLUS_DEP)
$(O)pf_qdot.OBJ:        $(@B).C         $(PF_QDOT_DEP)
$(O)pf_query.OBJ:       $(@B).C         $(PF_QUERY_DEP)
$(O)pf_rcaret.OBJ:      $(@B).C         $(PF_RCARET_DEP)
$(O)pf_rcaretund.OBJ:   $(@B).C         $(PF_RCARETUND_DEP)
$(O)pf_rho.OBJ:         $(@B).C         $(PF_RHO_DEP)
$(O)pf_rshoe.OBJ:       $(@B).C         $(PF_RSHOE_DEP)
$(O)pf_rtack.OBJ:       $(@B).C         $(PF_RTACK_DEP)
$(O)pf_slash.OBJ:       $(@B).C         $(PF_SLASH_DEP)
$(O)pf_slope.OBJ:       $(@B).C         $(PF_SLOPE_DEP)
$(O)pf_squad.OBJ:       $(@B).C         $(PF_SQUAD_DEP)
$(O)pf_star.OBJ:        $(@B).C         $(PF_STAR_DEP)
$(O)pf_stile.OBJ:       $(@B).C         $(PF_STILE_DEP)
$(O)pf_tilde.OBJ:       $(@B).C         $(PF_TILDE_DEP)
$(O)pf_times.OBJ:       $(@B).C         $(PF_TIMES_DEP)
$(O)pf_uarrow.OBJ:      $(@B).C         $(PF_UARROW_DEP)
$(O)pf_ucaret.OBJ:      $(@B).C         $(PF_UCARET_DEP)
$(O)pf_ustile.OBJ:      $(@B).C         $(PF_USTILE_DEP)
$(O)pf_utack.OBJ:       $(@B).C         $(PF_UTACK_DEP)
$(O)pf_utackjot.OBJ:    $(@B).C         $(PF_UTACKJOT_DEP)
$(O)po_dieresis.OBJ:    $(@B).C         $(PO_DIERESIS_DEP)
$(O)po_ditilde.OBJ:     $(@B).C         $(PO_DITILDE_DEP)
$(O)po_dot.OBJ:         $(@B).C         $(PO_DOT_DEP)
$(O)po_jot.OBJ:         $(@B).C         $(PO_JOT_DEP)
$(O)po_jotdot.OBJ:      $(@B).C         $(PO_JOTDOT_DEP)
$(O)po_slash.OBJ:       $(@B).C         $(PO_SLASH_DEP)
$(O)po_slope.OBJ:       $(@B).C         $(PO_SLOPE_DEP)
$(O)primfns.OBJ:        $(@B).C         $(PRIMFNS_DEP)
$(O)primspec.OBJ:       $(@B).C         $(PRIMSPEC_DEP)
$(O)qdwa.OBJ:           $(@B).C         $(QDWA_DEP)
$(O)qf_av.OBJ:          $(@B).C         $(QF_AV_DEP)
$(O)qf_cr.OBJ:          $(@B).C         $(QF_CR_DEP)
$(O)qf_dl.OBJ:          $(@B).C         $(QF_DL_DEP)
$(O)qf_dm.OBJ:          $(@B).C         $(QF_DM_DEP)
$(O)qf_dr.OBJ:          $(@B).C         $(QF_DR_DEP)
$(O)qf_error.OBJ:       $(@B).C         $(QF_ERROR_DEP)
$(O)qf_lc.OBJ:          $(@B).C         $(QF_LC_DEP)
$(O)qf_nc.OBJ:          $(@B).C         $(QF_NC_DEP)
$(O)qf_nl.OBJ:          $(@B).C         $(QF_NL_DEP)
$(O)qf_size.OBJ:        $(@B).C         $(QF_SIZE_DEP)
$(O)qf_sysid.OBJ:       $(@B).C         $(QF_SYSID_DEP)
$(O)qf_sysver.OBJ:      $(@B).C         $(QF_SYSVER_DEP)
$(O)qf_tc.OBJ:          $(@B).C         $(QF_TC_DEP)
$(O)qf_ts.OBJ:          $(@B).C         $(QF_TS_DEP)
$(O)qf_type.OBJ:        $(@B).C         $(QF_TYPE_DEP)
$(O)qf_ucs.OBJ:         $(@B).C         $(QF_UCS_DEP)
$(O)refcnt.OBJ:         $(@B).C         $(REFCNT_DEP)
$(O)reg.OBJ:            $(@B).C         $(REG_DEP)
!if "$(RESDEBUG)" == "1"
$(O)resdebug.OBJ:       $(@B).C         $(RESDEBUG_DEP)
!endif
$(O)savews.OBJ:         $(@B).C         $(SAVEWS_DEP)
$(O)sessman.OBJ:        $(@B).C         $(SESSMAN_DEP)
$(O)sort.OBJ:           $(@B).C         $(SORT_DEP)
$(O)strand.OBJ:         $(@B).C         $(STRAND_DEP)
$(O)symtab.OBJ:         $(@B).C         $(SYMTAB_DEP)
$(O)symtrans.OBJ:       $(@B).C         $(SYMTRANS_DEP)
$(O)syscmds.OBJ:        $(@B).C         $(SYSCMDS_DEP)
$(O)sysvars.OBJ:        $(@B).C         $(SYSVARS_DEP)
$(O)tabctrl.OBJ:        $(@B).C         $(TABCTRL_DEP)
$(O)tokenize.OBJ:       $(@B).C         $(TOKENIZE_DEP)
$(O)translate.OBJ:      $(@B).C         $(TRANSLATE_DEP)
$(O)ver.OBJ:            $(@B).C         $(VER_DEP)
$(O)yyfns.OBJ:          $(@B).C         $(YYFNS_DEP)

main.RC:                                $(MAIN_RCDEP)   $(ICONS)

ver.RC:                                 $(VER_RCDEP)

$(O)main.RES:           $(@B).RC        $(MAIN_RCDEP)
        @Set INCLUDE=$(I98);$(H);$(O)
        @if exist $@ del $@
        @$(RC) $(RCFLAGS) $(RCDEFINES) -r -fo$@ %s

$(BC)$(ENAME).HLP:      $(ENAME).RTF
        $(HLP) -o $@ -xr %s

$(L)$(ENAME).HLP:       $(BC)$(ENAME).HLP
        copy /y %s $@

$(WS)local.h:           editctrl.h   resource.h

# Build the Win32 version
OBJS=                       \
     $(O)assign.OBJ         \
     $(O)bjhash.OBJ         \
     $(O)common.OBJ         \
     $(O)convert.OBJ        \
     $(O)debug.OBJ          \
     $(O)dfnhdr.OBJ         \
     $(O)dispdbg.OBJ        \
     $(O)display.OBJ        \
     $(O)dtoa.obj           \
     $(O)editctrl.OBJ       \
     $(O)editfcn.OBJ        \
     $(O)editmat.OBJ        \
     $(O)editvec.OBJ        \
     $(O)errmsg.OBJ         \
     $(O)except.OBJ         \
     $(O)execdfn.OBJ        \
     $(O)fastbool.OBJ       \
     $(O)free.OBJ           \
     $(O)g_fmt.obj          \
     $(O)getreent.OBJ       \
     $(O)goto.obj           \
     $(O)immexec.OBJ        \
     $(O)main.OBJ           \
     $(O)parse.OBJ          \
     $(O)pf_bar.OBJ         \
     $(O)pf_circle.OBJ      \
     $(O)pf_colonbar.OBJ    \
     $(O)pf_comma.OBJ       \
     $(O)pf_cslope.OBJ      \
     $(O)pf_cstile.OBJ      \
     $(O)pf_cstar.OBJ       \
     $(O)pf_darrow.OBJ      \
     $(O)pf_dcaret.OBJ      \
     $(O)pf_deltastile.OBJ  \
     $(O)pf_domino.OBJ      \
     $(O)pf_dstile.OBJ      \
     $(O)pf_dtack.OBJ       \
     $(O)pf_dtackjot.OBJ    \
     $(O)pf_epsilon.OBJ     \
     $(O)pf_equal.OBJ       \
     $(O)pf_equalund.OBJ    \
     $(O)pf_index.OBJ       \
     $(O)pf_iota.OBJ        \
     $(O)pf_lcaret.OBJ      \
     $(O)pf_lcaretund.OBJ   \
     $(O)pf_lshoe.OBJ       \
     $(O)pf_ltack.OBJ       \
     $(O)pf_ndcaret.OBJ     \
     $(O)pf_nequal.OBJ      \
     $(O)pf_nucaret.OBJ     \
     $(O)pf_plus.OBJ        \
     $(O)pf_qdot.OBJ        \
     $(O)pf_query.OBJ       \
     $(O)pf_rcaret.OBJ      \
     $(O)pf_rcaretund.OBJ   \
     $(O)pf_rho.OBJ         \
     $(O)pf_rshoe.OBJ       \
     $(O)pf_rtack.OBJ       \
     $(O)pf_slash.OBJ       \
     $(O)pf_slope.OBJ       \
     $(O)pf_squad.OBJ       \
     $(O)pf_star.OBJ        \
     $(O)pf_stile.OBJ       \
     $(O)pf_tilde.OBJ       \
     $(O)pf_times.OBJ       \
     $(O)pf_uarrow.OBJ      \
     $(O)pf_ucaret.OBJ      \
     $(O)pf_ustile.OBJ      \
     $(O)pf_utack.OBJ       \
     $(O)pf_utackjot.OBJ    \
     $(O)po_dieresis.OBJ    \
     $(O)po_ditilde.OBJ     \
     $(O)po_dot.OBJ         \
     $(O)po_jot.OBJ         \
     $(O)po_jotdot.OBJ      \
     $(O)po_slash.OBJ       \
     $(O)po_slope.OBJ       \
     $(O)primfns.OBJ        \
     $(O)primspec.OBJ       \
     $(O)qdwa.OBJ           \
     $(O)qf_av.OBJ          \
     $(O)qf_cr.OBJ          \
     $(O)qf_dl.OBJ          \
     $(O)qf_dm.OBJ          \
     $(O)qf_dr.OBJ          \
     $(O)qf_error.OBJ       \
     $(O)qf_lc.OBJ          \
     $(O)qf_nc.OBJ          \
     $(O)qf_nl.OBJ          \
     $(O)qf_size.OBJ        \
     $(O)qf_sysid.OBJ       \
     $(O)qf_sysver.OBJ      \
     $(O)qf_tc.OBJ          \
     $(O)qf_ts.OBJ          \
     $(O)qf_type.OBJ        \
     $(O)qf_ucs.OBJ         \
     $(O)refcnt.OBJ         \
     $(O)reg.OBJ            \
!if "$(RESDEBUG)" == "1"
     $(O)resdebug.OBJ       \
!endif
     $(O)savews.OBJ         \
     $(O)sessman.OBJ        \
     $(O)sort.OBJ           \
     $(O)strand.OBJ         \
     $(O)symtab.OBJ         \
     $(O)symtrans.OBJ       \
     $(O)syscmds.OBJ        \
     $(O)sysvars.OBJ        \
     $(O)tabctrl.OBJ        \
     $(O)tokenize.OBJ       \
     $(O)translate.OBJ      \
     $(O)ver.OBJ            \
     $(O)yyfns.OBJ          \
     $(O)DBGBRK.OBJ         \
     $(O)main.RES

$(O)$(ENAME).EXE:       $(OBJS)         \
                        $(DEFFILE)      \
                        MAKEFILE
        @echo >NUL @<<$(O)main.CRF
$(OBJS)
/OUT:$(O)$(ENAME).EXE
/MAP:$(O)$(MAPFILE)
$(LIBS_WEXE) $(LIBS_EXT)
/DEF:$(DEFFILE)
<<KEEP
        @Set LIB=$(L98);$(L)
        @if exist $@ del $@
        @$(LD) $(LFLAGS_WEXE) @$(O)main.CRF
####    @strip -s $@
        @del $(O)$(@B).exp
        @del $(O)$(@B).lib
        @pkzip $(B)$(ENAME) $@ LICENSE $(BC)$(ENAME).HLP >NUL

$(L)$(ENAME).EXE:       $(O)$(ENAME).EXE
        @xc/r    %s      $@ >NUL
####    @ff $(B)$(ENAME)
        @dir $(B)$(ENAME).*|grep "$(ENAME)\."

zip:
        pkzip $(ZIPNAME) @nars2000.inp


$(O)$(MV).obj:          $(@B).c

$(O)$(MV).exe:          $(O)$(MV).obj
        @echo >NUL @<<$(O)$(MV).crf
$(O)$(MV).obj
/OUT:$(O)$(MV).exe
/MAP:$(O)$(MV).map
$(LIBS_WEXE) $(LIBS_EXT)
/DEF:$(MV).def
<<KEEP
        @Set LIB=$(L98);$(L)
        @if exist $@ del $@
        @$(LD) $(LFLAGS_WEXE) @$(O)$(MV).crf
        @del $(O)$(@B).exp
        @del $(O)$(@B).lib

$(L)$(MV).exe:          $(O)$(MV).exe
        @xc/r    %s     $@ >NUL

$(ENAME).ver:           $(O)$(ENAME).exe
        @$(O)$(MV).exe $(O)$(ENAME).exe

